# Data
path: D:\Interns\Prabhanjan\extended-keypoints-yolo\
train: D:\Interns\Prabhanjan\extended-keypoints-yolo\data\images\train  # train images
val: D:\Interns\Prabhanjan\extended-keypoints-yolo\data\images\val  # val images


# Keypoints


#   26 body keypoints
#    {0,  "Nose"},
#    {1,  "LEye"},
#    {2,  "REye"},
#    {3,  "LEar"},
#    {4,  "REar"},
#    {5,  "LShoulder"},
#    {6,  "RShoulder"},
#    {7,  "LElbow"},
#    {8,  "RElbow"},
#    {9,  "LWrist"},
#    {10, "RWrist"},
#    {11, "LHip"},
#    {12, "RHip"},
#    {13, "LKnee"},
#    {14, "Rknee"},
#    {15, "LAnkle"},
#    {16, "RAnkle"},
#    {17,  "Head"},
#    {18,  "Neck"},
#    {19,  "Hip"},
#    {20, "LBigToe"},
#    {21, "RBigToe"},
#    {22, "LSmallToe"},
#    {23, "RSmallToe"},
#    {24, "LHeel"},
#    {25, "RHeel"},


kpt_shape: [26, 3]  # [number of keypoints, number of dim] [kp.x, kp.y, kp.confidence]
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15, 17, 18, 19, 21, 20, 23, 22, 25, 24]

# Classes
names:
  0: people
